opt_in_rules:
- force_unwrapping
- force_try
- force_cast

excluded:
- Carthage
- Swiftgen
- Pods
nesting:
  type_level: 3

colon:
  severity: error

closure_end_indentation:
  severity: error

closure_parameter_position:
  severity: error

comma:
  severity: error

discouraged_direct_init:
  severity: error

closure_spacing:
  severity: error

control_statement:
  severity: warning

compiler_protocol_init:
  severity: warning

empty_parentheses_with_trailing_closure:
  severity: error

cyclomatic_complexity:
  warning: 12
  error: 15

discouraged_direct_init:
  severity: warning

empty_parameters:
  severity: error

explicit_init:
  severity: error

fatal_error_message:
  severity: error

file_length: 800

first_where:
  severity: warning

for_where:
  severity: warning

force_try:
  severity: error

force_unwrapping:
  severity: error

force_cast:
  severity: error

function_body_length:
- 100 # warning
- 101 # error

function_parameter_count: 7

generic_type_name:
  severity: error

implicit_getter:
  severity: warning

implicitly_unwrapped_optional:
  severity: error

joined_default_parameter:
  severity: error

large_tuple: 6

leading_whitespace:
  severity: error

legacy_cggeometry_functions:
  severity: error

legacy_constant:
  severity: error

legacy_constructor:
  severity: error

line_length:
  warning: 200
  error: 500
  ignores_comments: true

mark:
  severity: warning

multiline_parameters:
  severity: error

multiple_closures_with_trailing_closure:
  severity: warning

number_separator:
  severity: warning

object_literal:
  severity: error

opening_brace:
  severity: error

operator_usage_whitespace:
  severity: error

operator_whitespace:
  severity: error

overridden_super_call:
  severity: warning

private_over_fileprivate:
  severity: warning

prohibited_super_call:
  severity: warning

protocol_property_accessors_order:
  severity: error

redundant_discardable_let:
  severity: error

redundant_nil_coalescing:
  severity: error

redundant_void_return:
  severity: error

return_arrow_whitespace:
  severity: error

shorthand_operator:
  severity: warning

single_test_class:
  severity: error

statement_position:
  severity: error

switch_case_on_newline:
  severity: warning

syntactic_sugar:
  severity: warning

trailing_comma:
  severity: error

trailing_newline:
  severity: warning

trailing_semicolon:
  severity: error

trailing_whitespace:
  severity: warning

type_body_length: 1_000

type_name:
  severity: error
  min_length: 4
  max_length: 60

unneeded_parentheses_in_closure_argument:
  severity: warning

unused_closure_parameter:
  severity: warning

unused_enumerated:
  severity: warning

unused_optional_binding:
  severity: warning

valid_ibinspectable:
  severity: warning

variable_name:
  max_length:
    warning: 30
    error: 40
  min_length:
    warning: 2 

vertical_parameter_alignment:
  warning: 4
  error: 6
  severity: error

vertical_parameter_alignment_on_call:
  severity: error

vertical_whitespace:
  severity: warning

weak_delegate:
  severity: error

xctfail_message:
  severity: error

sorted_first_last:
  severity: warning

sorted_imports:
  severity: warning

override_in_extension:
  severity: error

yoda_condition:
  severity: warning

discouraged_optional_boolean:
  severity: error
